# Numpy Notes<br>
<span style="color:red">Numpy stands for numerical python. It is used for fast and efficient scientific and numerical computation using
 its powerful n-dimensional array and matrices.<br> It is simply used for mathematical, logical and vectoriation(performing operation
 on enitre array) operations on array.
 </span>

<h1>Basic Numpy

<h2 style ="color:blue"> 1.Creating a numpy array and checking data type.

In [2]:
import numpy as np 

In [8]:
array = [1,2,3,4]
tuples = (5,6,7,8)
array = np.array(array)
tuples = np.array(tuples)
print(array*2)
print(tuples*3)

[2 4 6 8]
[15 18 21 24]


In [6]:
arr1 = np.array([1,2,3])
print(arr1.dtype)
print(arr1.shape)
arr2 = arr1.astype('f')
print(arr2.dtype)

int64
(3,)
float32


<div style = "color:green; background-color:lightblue"> dtype method helps to find the data type of given array and astype helps to change <br>
 the datatype.</div>

<h2 style="color:blue">2.Creating multi-dimensional array

In [8]:
array = np.array([1,2,3])
print(array.ndim)
print(array[1])

1
2


<div style = 'color:green ; background-color:lightblue'>It is an one dimensional array. It has only one row.</div>

In [10]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(array.ndim)
print(array[1,1])
print(array[1][1])

2
5
5


<div style = 'color:green ; background-color:lightblue'>It is 2D array. It has row and column. Each element exist in the form of [i][j] 
or [i,j]<br>
determined by the size of the array. The given array is of 3 by 3 so its second elemnt is [0][1] = 2.</div>

In [9]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                  [[10,11,12],[13,14,15],[16,17,18]],
                  [[19,20,21],[22,23,24],[25,26,27]]])
print(array.ndim)
print(array[1][1][1])
print(array[2,2,2])
                  

3
14
27


<div style = 'color:green ; background-color:lightblue'>It is 3D array. It has three indexes [depth][rows][columns]. In 3D arrays, 2D arrays <br> are stacked upon
to give depth.</div>

In [52]:
array = np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


<div style = 'color:green ; background-color:lightblue'>We can create a array having all the elements zeros using np.zeros function.<br>
We pass the tuple of rows and columns as argument to the function.</div>

In [53]:
array = np.random.random((2,3))
print(array)

[[0.28663869 0.46502085 0.52129593]
 [0.52313046 0.9750572  0.85353075]]


<div style = 'color:green ; background-color:lightblue'>We can create array of random floats using random function by passing tuple <br>
of rows and columns as arguments. The reason we use random.random is because np.random is module in numpy library<br>
whereas, random() is a function inside that module.</div>

In [55]:
print(np.arange(-5,6))

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


<div style = 'color:green ; background-color:lightblue'>It will create a range of numbers where the first arguemtn is inclusive but the <br>
second one is exclusive. It is similar to range function .</div>

<h2 style = 'color:blue'>3.Slicing

In [32]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(array[0])
print(array[0:3])

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<div style = 'color:green ; background-color:lightblue'>
We access array and index in the form [start:end:step-row,start:end:step-column] .<br>First we got the first row with index 0 and then we got the first,second and third row <br>
starting with the index 0 and ending exclusive 3.</div|>

In [35]:
print(array[:,2])
print(array[:,0:3])

[3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<div style = 'color:green ; background-color:lightblue'>The first index is for row, where we select the every row with : and then put , <br>
and now we have index for column, 0:3 gave us the first three columns.</div>

In [37]:
print(array[0:2,0:2])

[[1 2]
 [4 5]]


<div style = 'color:green ; background-color:lightblue'>It gave us the matrix formed by first two row and first two column. ',' helps to 
<br>determine both row and column to select the specific part of the array.
<br> Simply, array[start:end:step for row, start:end:step for column].</div>

In [13]:
array1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                  [[10,11,12],[13,14,15],[16,17,18]],
                  [[19,20,21],[22,23,24],[25,26,27]]])
print(array1[0:2,0:2,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]


<span style = "color:Green"> This is a slicing of 3D array.</span>

In [6]:
origarr = np.arange(10)
newarr = origarr[:5]
newarr[4] = 0
print(newarr)
print(origarr)

[0 1 2 3 0]
[0 1 2 3 0 5 6 7 8 9]


<div style = "background-color:lightblue; color:green">While slicing array in numpy. The operation performed on newarray will
have effect on the original array as well, since numpy doesn't copy the values from original array to new arary.</div>

In [7]:
origarr = np.arange(10)
newarr = origarr[:5].copy()
newarr[4] = 0
print(newarr)
print(origarr)

[0 1 2 3 0]
[0 1 2 3 4 5 6 7 8 9]


<div style = "background-color:lightblue; color:green">To avoid this we can use copy method.</div>

<h2 style = 'color:blue'>4. shapes and reshaping numpy array.

In [5]:
arr = np.array([[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]]])
print(arr.shape)
arr1 = np.arange(0,27)
arr2 = arr1.reshape(3,9)
print(arr2)

(2, 2, 3)
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


<div style = 'color:green ; background-color:lightblue'>Here we created a normal array having 27 elements 0-26<br>
using arange function, then we reshaped it into 3 by 9 array using reshpape method. The size must be equal to number of elements.<br>
The shape of the array is (2,2,3), it means there are 2 elements along 0-axis(depth), 2 elements along 1-axis(rows) and 3 elements along 2-axis(column). </div>

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)
print(arr.reshape(3,2))
print(arr.reshape(-1))

6
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


<div style = 'color:green ; background-color:lightblue'>This time we took 2D array which is of shape 2 by 3. We then rehspape<br>
it into 3 by 2 array. Here the size of both the arrays are same that is 6. -1 helps to flatten the array in 1D.</div>

<h2 style = "color:blue">5.Iterating over arrays

In [14]:
arr = np.arange(0,6)
for a in arr:
    print(a)

0
1
2
3
4
5


<div style = 'color:green ; background-color:lightblue'>Iterating over 1D array is as same as we do with the python list.</div>

In [16]:
arr = np.arange(0,6)
arr2 = arr.reshape(2,3)
for a in arr2:
    print(a)

for a in arr2:
    for b in a:
        print(b)
    

[0 1 2]
[3 4 5]
0
1
2
3
4
5


<div style = 'color:green ; background-color:lightblue'>For 2D array using just one loop give us the list of rows. If we want to 
print each element we can simply use two loops. One will read each rows of 2D array and another one will read each element in those arrays.</div>

In [20]:
arr = np.arange(1,28)
arr3 = arr.reshape(3,3,3)
for a in arr3:
    print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


<div style = 'color:green ; background-color:lightblue'>This is for accessing each 2D arrays in 3D arrays using one loop.</div>

In [22]:
arr = np.arange(1,28)
arr3 = arr.reshape(3,3,3)
for a in arr3:
    for b in a:
        print(b)
        

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
[13 14 15]
[16 17 18]
[19 20 21]
[22 23 24]
[25 26 27]


<div style = "color:green; background-color:lightblue">This is for accessing each 1D arrays in those 2D arrays.</div>

In [23]:
arr = np.arange(1,28)
arr3 = arr.reshape(3,3,3)
for a in arr3:
    for b in a:
        for c in b:
            print(c)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


<div style = "color:green; background-color:lightblue">This is for accessing each individual elements.</div>

<h2 style = "color:blue">6.Joining numpy arrays.

In [33]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
comb = np.concatenate((arr1,arr2))
print(comb)
arr3 = np.array([[1,2],
                 [3,4]])
arr4 = np.array([[5,6],
                 [7,8]])

print(np.concatenate((arr3,arr4),axis = 0)) #by default
print(np.concatenate((arr3,arr4),axis = 1))

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


<div style = "color:green; background-color:lightblue">Here, we joined two arrays using concatenate method.<br>
When there is axis = 0 , which is a default value, the arrays are joined rows wise. It is like array1 is stacked upon
array2. <br>
When there is axis = 1, the arrays are joined column wise. It is like array2 is placed right of array1 and joined.</div>

In [35]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,12,13,14,15])
comb = np.stack((arr1,arr2),axis = 0)
print(comb)
print(np.stack((arr1,arr2),axis = 1))

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]]


<div style = "color:green; background-color:lightblue">Here, we joined two arrays using stack method. The only difference is that
using stack method adds one more dimension to the joined array.<br>First we joined two 1D arrays and we got 2D arrays.
</div>

In [36]:
arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[5,6],
                 [7,8]])
print(np.stack((arr1,arr2),axis = 2))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


<div style = "color:green; background-color:lightblue">As using stack give us one more dimension, when we create a combined array
using two 2D arrays, we get a 3D arrays and the way elements are combined can be modified with one more axis that is axis = 2
which join elements as two 2D arrays are stack upon each other. If this seems to be confusing you can take two piece of paper, make
each 2D array one each paper and stack them upon one another and compare the elements you get from the given program.</div>

In [40]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.hstack((a,b)))
print(np.vstack((a,b)))
print(np.dstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


<div style = "color:green; background-color:lightblue">hstack is the shorcut method for horizontal stack , vstack is the shortcut for
vertical stack and dstack is shortcut for depth stack.</div>

<h2 style = "color:blue">7.Splitting Numpy Array

In [3]:
bigarr = np.array([1,2,4,5,6,7,8,9,10])
smallarr = np.array_split(bigarr,2)
print(smallarr)
for a in smallarr:
    print(a)

[array([1, 2, 4, 5, 6]), array([ 7,  8,  9, 10])]
[1 2 4 5 6]
[ 7  8  9 10]


<div style = "color:green; background-color:lightblue">array_split takes two argument, first the array which we want to split and second one
the number of array we want to get after splitting. This function split the array and store it into a list. So, to access splitted array we need to loop.</div>

In [4]:
bigarr = np.array([[1,2,3],
                   [4,5,6]])
smallarr = np.array_split(bigarr,2)
print(smallarr)
for a in smallarr:
    for b in a:
        print(b)

[array([[1, 2, 3]]), array([[4, 5, 6]])]
[1 2 3]
[4 5 6]


<div style = "background-color:lightblue; color:green">Similarly, we can also split 2D arrays.</div>

<h2 style = "color:blue">8.Search a numpy array for a value</div>

In [7]:
arr = np.array([1,2,3,4,5,6,7,8])
ser = np.where(arr == 7)
print(ser)

(array([6]),)


<div style = "background-color:lightblue; color:green">At index 6 the value 7 is present.</div>

In [9]:
arr = np.array([[1,2,3],
                [4,5,6]])
ser = np.where( arr == 5)
print(ser)

(array([1]), array([1]))


<div style = "background-color:lightblue; color:green">The value 5 is present at second array and second column.</div>

<h2 style = "color:blue">9.Sorting Numpy Arrays

In [11]:
oneDarray = np.array([1,2,3,4,5,6,7])
twoDarray = np.array([[1,2,3],
                    [4,5,6]])
str = np.array(['cat','dog','zebra','apple','bull'])
print(np.sort(oneDarray))
print(np.sort(twoDarray))
print(np.sort(str))


[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]]
['apple' 'bull' 'cat' 'dog' 'zebra']


<div style = "background-color:lightblue; color:green">This is how you can simply array of integer or string using sort method.</div>

<h2 style="color:blue">10.Boolean Indexing</h2>

In [17]:
 names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]) 

data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
print(names == "Bob")
data[names == "Bob"]

[ True False False  True False False False]


array([[4, 7],
       [0, 0]])

<div style = "background-color:lightblue; color:green">names == "Bob", it will compare each element of the array name with Bob and return a
boolean array consisting of values True or False.<br>
Now this boolean array can be used to select particular rows or columns where the boolean value is true.</div>

In [19]:
 names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]) 

data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
~(names == "Bob")
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

<div style = "background-color:lightblue; color:green">Tilde ~ is a negation operator which can be used to negate the given
condition.</div>

In [22]:
 names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]) 

data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
cond = (names == "Bob") | (names == "Will")
data[cond]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

<div style = "background-color:lightblue; color:green">In numpy we use & for and and | for or, for multiple conditions.</div>

In [25]:
 names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]) 

data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
cond = (names == "Bob") | (names == "Will")
data[cond] = 0
print(data)

[[  0   0]
 [  0   2]
 [  0   0]
 [  0   0]
 [  0   0]
 [-12  -4]
 [  3   4]]


<h2 style = "color:blue">11.Fancy Indexing

<div style = "background-color:lightblue; color:green">Fancy indexing refers to selecting elements from the array using integer array or list
instead of single number.</div>

In [61]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i

print(arr)
print("___________")
print(arr[[1,5,6]])
print("___________")
print(arr[:,[1,3,2]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
___________
[[1. 1. 1. 1.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]]
___________
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]]


<div style = "background-color:lightblue; color:green">In the above example we have passed a list of integer containing 1 and 2 which 
selects the second and third rows from the array.</div>

In [44]:
arr = np.arange(32).reshape((8,4))
print(arr)
print("___________________")
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
___________________
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


<div style = "background-color:lightblue; color:green">First we selected the 1,2,5 and 7 th array by using list of integers then
from those array we selected particular columns that are 0,3,1 and 2 nd column by another list of integers. This is how fancy indexing works.</div>

<h2 style = "color:blue">12.Transposing and swapping axes</h2>

In [46]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr.T)
print(arr.swapaxes(0,1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


<div style = "background-color:lightblue; color:green">This method is often used when doing matrix operations. It just swap the row axis(0) to column axis(1).</div>

<h2 style = "color:blue">13.Array oriented programming with arrays

In [76]:
arr = np.arange(-5,5)
xs,ys = np.meshgrid(arr,arr)
print(xs,ys)

z = np.sqrt(xs**2 + ys**2)
print(z)
        

[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]] [[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]]
[[7.07106781 6.40312424 5.83095189 5.38516481 5.09901951 5.
  5.09901951 5.38516481 5.83095189 6.40312424]
 [6.40312424 5.65685425 5.         4.47213595 4.12310563 4.
  4.12310563 4.47213595 5.         5.65685425]
 [5.83095189 5.         4.24264069 3.60555128 3.16227766 3.
  3.16227766 3.60555128 4.24264069 5.        ]
 [5.38516481 4.47

<div style = "background-color:lightblue; color:green">meshgrid function simply takes two one D arrays and creates a 2D array
consisting of all possible coordinates pair upto the given range. It can be used to evaluate functions by putting x and y coordinates and 
showing it in the cartesian plane. xs creates a matrix by copying the 1D matrix rows wise and ys creates a matrix by copying the 1D matrix
column wise, combining both we get all the possible coordinates pair.</div>

<h2 style = " color:blue">14.Expressing conditional logic as array operation

In [4]:
xarr = np.array([25, 25, 25, 25, 25]) 
yarr = np.array([10, 10, 10, 10, 10]) 
cond = np.array([True, False, True, True, False])
print(np.where(cond,xarr,yarr))

[25 10 25 25 10]


<div style ="background-color:lightblue;color:green">We can consider two arrays consisting practical marks of five students.
Frist one is full marks for student those who were present which is given True in the condition array and those who were absent is given false
in the condition array.Now where method takes three arguemtns first one is the condition, whereeven the condition is true it takes element from
first array arguement and wheneven the condition is false it takes element from second array arguement.This is how we express condtional logic
using array operation.</div>

In [11]:
arr = np.arange(-10,10).reshape(5,4)
print(arr)
print(np.where(arr < 0,2,arr))


[[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]
 [  6   7   8   9]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 0 1]
 [2 3 4 5]
 [6 7 8 9]]


<div style ="background-color:lightblue; color:green">Here we generated 5 by 4 matrix and replaced all the negative numbers with 2 using
where method.</div>

<h2 style ="color:blue">15.Some mathematical and statistical methods

In [18]:
arr = np.arange(-10,10).reshape(5,4)
print(arr)
print(arr.sum())
print(np.sum(arr,axis =1))
print(arr.mean())
print(np.mean(arr,axis =1))

[[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]
 [  6   7   8   9]]
-10
[-34 -18  -2  14  30]
-0.5
[-8.5 -4.5 -0.5  3.5  7.5]


<div style ="background-color:lightblue; color:green">sum and mean method also takes second arguement to calculate sum and mean rows or column wise 
respectively.<br> These are reduction function that aggreates values into one and operates on single array.</div>

In [20]:
array = np.arange(-10,10).reshape(4,5)
print(np.cumsum(array))
print(np.cumprod(array))

[-10 -19 -27 -34 -40 -45 -49 -52 -54 -55 -55 -54 -52 -49 -45 -40 -34 -27
 -19 -10]
[     -10       90     -720     5040   -30240   151200  -604800  1814400
 -3628800  3628800        0        0        0        0        0        0
        0        0        0        0]


<div style ="background-color:lightblue; color:green">Normal sum and prod method gives a single scalar result whereas cumsum and cumprod returns
an array of same size with cumulative result.</div>

In [23]:
array = np.arange(-10,10).reshape(5,4)
print(np.std(array))
print(np.var(array))
print(np.max(array))
print(np.min(array))

5.766281297335398
33.25
9
-10


<div style ="background-color:lightblue; color:green">Here are few more method to calculate standard deviation,variance,max value and min value.</div>

<h2 style ="color:blue">16.Methods for boolean arrays

In [30]:
arr = np.arange(-10,10).reshape(4,5)
print((arr > 0).sum())

9


In [32]:
bools = np.array([False, False, True, False]) 
print(bools.any())
print(bools.all()) 

True
False


<div style ="background-color:lightblue; color:green">any method checks if any value in the array is true and all method checks if all values are ture. </div>

<h2 style ="color:blue">17.Set logics

In [36]:
strr = np.array(['apple','cat','doggy','apple','doggy','cat'])
intt = np.arange(-5,5)
print(np.unique(strr))
print(np.unique(intt))

['apple' 'cat' 'doggy']
[-5 -4 -3 -2 -1  0  1  2  3  4]


<div style ="background-color:lightblue; color:green">unique return array of sorted unique elements from the array.</div>

In [38]:
strr = np.array(['apple','cat','doggy','apple','doggy','cat'])
intt = np.arange(-5,5)
newstr = sorted(set(strr))
for a in newstr:
    print(a)

apple
cat
doggy


<div style ="background-color:lightblue; color:green">It can be done by normal python methods also but numpy method is much faster.</div>

In [44]:
setA = np.array(['apple','cat','doggy','apple','doggy','cat'])
setB = np.array(['elephant','bat','apple','doggy'])
print(np.union1d(setA,setB))
print(np.intersect1d(setA,setB))
print(np.isin(setA,setB))
print(np.setdiff1d(setA,setB))

['apple' 'bat' 'cat' 'doggy' 'elephant']
['apple' 'doggy']
[ True False  True  True  True False]
['cat']


<div style ="background-color:lightblue; color:green">i.union return array of elements contained in both arrays.<br>
ii.intersect1d returns array of the common elements contained in both.<br>
iii.isin return boolean array indicating if elements of first array argument is contained in second array arguement.<br>
iv.setdiff1d returns array of elements that is contained in first arrray arguement but not in second one.</div>

<h2 style ="color:blue">18.Matrix operations</h2>

In [49]:
mat = np.array([1,3,4,4])
matt = np.array([12,3,5,34])
print(np.dot(mat,matt))
matA = np.array([[1,2],
                 [3,4]])
matB = np.array([[3,4],
                 [1,2]])
print(np.dot(matA,matB))

177
[[ 5  8]
 [13 20]]


<div style ="background-color:lightblue; color:green">dot method helps to calculate the product of two matrices.</div>

<h1> Advance Numpy

<h2 style="color:blue">1.Broadcasting

<div style ="background-color:lightblue; color:green">Broadcasting is the set of rules NumPy uses to apply arithmetic (and other operations) between arrays of different shapes.

Instead of explicitly copying data to match shapes, NumPy stretches the smaller array virtually (without actually using extra memory) so that element-wise operations can be performed.</div>

In [55]:
arr = np.array([3,4,3])
print(arr*5)

[15 20 15]


<div style ="background-color:lightblue; color:green">Here numpy broadcast 5 into [5,5,5] to match the shape of the array to perform multiplication.
</div>

<div style ="background-color:lightblue; color:green">Rules for broadcasting<br>
i.The size of the dimensions of the array must be same or one of them must be of size 1.<br>
ii. Compare the dimensions from the right and missing dimenion is condidered 1.
<br>Example: (3,) broadcasted to (1,3) and (3,1) are compatible and resulting array is (3,3)</div>

In [62]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],
                 [4,5,5],
                 [4,5,6]])
print(arr1+arr2)

[[2 4 6]
 [5 7 8]
 [5 7 9]]


<div style ="background-color:lightblue; color:green">arr1 broadcasted to [[1,2,3],[1,2,3],[1,2,3]].</div>

<h2 style = "color:blue">2.ufunc

<div style="background-color:lightblue;color:green">ufunc stands for universal function. They are numpy functions that take arrays as arguemtent
and perform element-wise operations faster and efficient than using explicit loops.</div>

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
arr3 = np.array([4,5,3])
np.add(arr1,arr2,arr3)

array([4, 6, 8])

<div style="background-color:lightblue;color:green">Difference between np.add() and np.sum().<br>
Here sum() is a reduction function that aggregates values from single array, whereas add is a universal function that perform element-wise operations between multiple arrays.</div>

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.power(arr1,2))


[-2 -2 -2]
[ 3  8 15]
[0.33333333 0.5        0.6       ]
[1 4 9]


In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
print(np.add.reduce(arr1))
print(np.multiply.accumulate(arr2))

6
[ 3 12 60]


<div style="background-color:lightblue;color:green">Here we have used reduce and accumulate methods to aggregate values as universal functions
operates on two or more arrays. Also, add.reduce() acts and sum() function and add.accumulate acts as cumsum().</div>

<h2 style="color:blue">2.1 Declaring your own ufunc

In [16]:
def my_add(x,y):
    return x+y

addition = np.vectorize(my_add)
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
print(addition(arr1,arr2))

[4 6 8]


In [17]:
def power(x,y):
    return x**y

pow = np.vectorize(power)
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
print(pow(arr1,arr2))

[  1  16 243]


<div style="background-color:lightblue;color:green">Here we can use vectorize method to create a python function that work as ufunc that takes
arrays and perform element-wise operation. But it is not actually as fast as normal ufunc.</div>